CREATE INDEX "account_user_id_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "account_provider_account_idx" ON "account" USING btree ("provider_id","account_id");--> statement-breakpoint
CREATE INDEX "account_expires_at_idx" ON "account" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "audit_log_user_id_idx" ON "audit_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "audit_log_action_idx" ON "audit_log" USING btree ("action");--> statement-breakpoint
CREATE INDEX "audit_log_entity_type_idx" ON "audit_log" USING btree ("entity_type");--> statement-breakpoint
CREATE INDEX "audit_log_entity_id_idx" ON "audit_log" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "audit_log_created_at_idx" ON "audit_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "audit_log_entity_idx" ON "audit_log" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "audit_log_user_action_idx" ON "audit_log" USING btree ("user_id","action");--> statement-breakpoint
CREATE INDEX "audit_log_action_created_at_idx" ON "audit_log" USING btree ("action","created_at");--> statement-breakpoint
CREATE INDEX "partner_members_user_id_idx" ON "partner_members" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "partner_members_partner_id_idx" ON "partner_members" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "partner_members_is_active_idx" ON "partner_members" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "partner_members_role_idx" ON "partner_members" USING btree ("role");--> statement-breakpoint
CREATE INDEX "partner_members_invited_by_idx" ON "partner_members" USING btree ("invited_by");--> statement-breakpoint
CREATE INDEX "partner_members_partner_active_idx" ON "partner_members" USING btree ("partner_id","is_active");--> statement-breakpoint
CREATE INDEX "partner_members_user_active_idx" ON "partner_members" USING btree ("user_id","is_active");--> statement-breakpoint
CREATE INDEX "partner_members_partner_role_active_idx" ON "partner_members" USING btree ("partner_id","role","is_active");--> statement-breakpoint
CREATE INDEX "partner_requests_user_id_idx" ON "partner_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "partner_requests_status_idx" ON "partner_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "partner_requests_business_email_idx" ON "partner_requests" USING btree ("business_email");--> statement-breakpoint
CREATE INDEX "partner_requests_reviewed_by_idx" ON "partner_requests" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX "partner_requests_partner_id_idx" ON "partner_requests" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "partner_requests_created_at_idx" ON "partner_requests" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "partner_requests_reviewed_at_idx" ON "partner_requests" USING btree ("reviewed_at");--> statement-breakpoint
CREATE INDEX "partner_requests_status_created_at_idx" ON "partner_requests" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "partner_requests_status_reviewed_at_idx" ON "partner_requests" USING btree ("status","reviewed_at");--> statement-breakpoint
CREATE INDEX "partners_slug_idx" ON "partners" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "partners_status_idx" ON "partners" USING btree ("status");--> statement-breakpoint
CREATE INDEX "partners_email_idx" ON "partners" USING btree ("email");--> statement-breakpoint
CREATE INDEX "partners_created_by_idx" ON "partners" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "partners_created_at_idx" ON "partners" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "partners_status_created_at_idx" ON "partners" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "session" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "session_token_idx" ON "session" USING btree ("token");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_platform_role_idx" ON "users" USING btree ("platform_role");--> statement-breakpoint
CREATE INDEX "users_status_idx" ON "users" USING btree ("status");--> statement-breakpoint
CREATE INDEX "users_active_partner_idx" ON "users" USING btree ("active_partner_id");--> statement-breakpoint
CREATE INDEX "users_created_at_idx" ON "users" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "users_status_role_idx" ON "users" USING btree ("status","platform_role");--> statement-breakpoint
CREATE INDEX "users_email_verified_idx" ON "users" USING btree ("email_verified");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "verification_value_idx" ON "verification" USING btree ("value");--> statement-breakpoint
CREATE INDEX "verification_expires_at_idx" ON "verification" USING btree ("expires_at");--> statement-breakpoint
ALTER TABLE "partner_members" ADD CONSTRAINT "partner_members_user_partner_unique" UNIQUE("user_id","partner_id");