CREATE INDEX "partner_status_createdAt_idx" ON "partner" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "idx_public_listings_id_expires" ON "car_listing" USING btree ("expires_at","id") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_listings_newest" ON "car_listing" USING btree ("original_published_at" DESC NULLS LAST,"published_at" DESC NULLS LAST,"created_at" DESC NULLS LAST) WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_listings_price_asc" ON "car_listing" USING btree ("price","created_at" DESC NULLS LAST) WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_listings_price_desc" ON "car_listing" USING btree ("price" DESC NULLS LAST,"created_at" DESC NULLS LAST) WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_make" ON "car_listing" USING btree ("make","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_model" ON "car_listing" USING btree ("model","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_trim" ON "car_listing" USING btree ("trim","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_emirate" ON "car_listing" USING btree ("emirate","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_specs" ON "car_listing" USING btree ("specs","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_body_type" ON "car_listing" USING btree ("body_type","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_fuel_type" ON "car_listing" USING btree ("fuel_type","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_transmission" ON "car_listing" USING btree ("transmission","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_engine_size" ON "car_listing" USING btree ("engine_size","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_exterior_color" ON "car_listing" USING btree ("exterior_color","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_interior_color" ON "car_listing" USING btree ("interior_color","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_seller_type" ON "car_listing" USING btree ("seller_type","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_year" ON "car_listing" USING btree ("year","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_mileage" ON "car_listing" USING btree ("mileage","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;--> statement-breakpoint
CREATE INDEX "idx_public_facet_price" ON "car_listing" USING btree ("price","expires_at") WHERE moderation_status = 'approved' AND lifecycle_status = 'active' AND needs_remoderation = false;