-- Drops indexes flagged as unused by Neon DB Advisor.
-- Each statement is separated to allow CONCURRENTLY in migration runners.
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_staff_userId_partnerId_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."listing_view_listingId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."conversation_participant_userId_isArchived_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."consignment_funnel_staffId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."consignment_funnel_partnerId_staffId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_profile_consignment_mode_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."feedback_userId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."feedback_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."feedback_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."verification_identifier_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."vin_publication_history_vin_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."kyc_record_userId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."kyc_record_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_favorite_listingId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_profile_phone_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_profile_location_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_profile_kyc_verified_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."audit_log_entityType_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."audit_log_entityId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."audit_log_action_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."audit_log_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."audit_log_severity_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."audit_log_entityType_entityId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_email_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_phone_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_trade_license_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_is_verified_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_emirate_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_location_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_primaryContactId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_accountManagerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_request_userId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_request_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_request_reviewedBy_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_request_tradeLicense_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_request_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_review_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_review_rating_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_review_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_staff_userId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_staff_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_staff_role_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."vin_publication_history_userId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_public_search_originalPublishedAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_originalPublishedAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_superlike_quota_userId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_superlike_quota_periodEndDate_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_slug_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_transmission_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_emirate_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."listing_price_history_listingId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."listing_price_history_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."listing_view_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."listing_view_sessionId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_userId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_slotId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_status_scheduledStartTime_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_partnerId_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_partnerId_scheduledDate_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_userId_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_confirmationToken_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_confirmedBy_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_slot_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_slot_listingId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_slot_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_slot_startTime_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_slot_partnerId_status_startTime_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_availability_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_availability_dayOfWeek_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_availability_isActive_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_booking_settings_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_booking_settings_bookingEnabled_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."conversation_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."kyc_record_diditSessionId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."kyc_record_documentHash_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."passkey_credentialID_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_showroom_slug_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_showroom_isPublished_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_showroom_viewCount_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_showroom_lastEditedBy_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."communications_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."communications_type_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."communications_email_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."communications_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."communications_isRead_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_superlike_listingId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_city_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_favorite_userId_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_superlike_userId_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."kyc_record_status_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_partnerId_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."ban_appeal_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_moderationStatus_lifecycleStatus_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_emirate_lifecycleStatus_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_userId_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_userId_scheduledStartTime_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."user_stripeCustomerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_moderationStatus_lifecycleStatus_updatedAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_updatedAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_public_search_publishedAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."consignment_funnel_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."consignment_funnel_isActive_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_slug_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."push_device_token_user_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."push_device_token_platform_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."push_device_token_is_active_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."push_notification_preferences_user_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."notification_user_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."notification_user_created_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."notification_type_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."feedback_reviewedBy_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."communications_assignedTo_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."communications_resolvedBy_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_request_partnerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."conversation_initiatedBy_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."conversation_lastMessageSenderId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."vin_publication_history_currentListingId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_userId_listingId_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_userId_status_startEnd_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_userId_cancelledBy_cancelledAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_stripeCustomerId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_tier_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_availability_staffUserId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_booking_settings_staffUserId_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_listings_newest";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_listings_price_asc";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."incident_update_incident_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."service_health_service_checked_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."status_incident_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."status_incident_started_at_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_status_createdAt_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."booking_partnerId_scheduledDate_status_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."partner_showroom_published_date_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_openToConsignment_publicish_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."car_listing_moderationStatus_lifecycleStatus_publishedAt_create";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."service_health_checked_at_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_facet_trim";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_facet_body_type";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_facet_transmission";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_facet_engine_size";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_facet_exterior_color";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_facet_interior_color";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_public_facet_seller_type";
